BOOL IsDriverRunning(const WCHAR* driver_name);
BOOL DriverExists(LPCSTR lpDriverName);
BOOL IsEndPoint();
BOOL IsComodo2();
BOOL IsComodo3();
BOOL IsAshampoo();
BOOL IsADAware();
BOOL IsSophos32();
BOOL IsDeepFreeze();
BOOL IsAvira();
BOOL IsPCTools();
BOOL IsBitDefender();
BOOL IsBitDefenderAVPlus();
BOOL IsBlink();
BOOL IsSunBeltPF();
BOOL IsRising();
BOOL IsZoneAlarm();
BOOL IsMcAfee();
BOOL IsPGuard();
BOOL IsTrend();
BOOL IsPanda64();
BOOL IsPanda();
BOOL IsAVG();
BOOL IsAVG_IS();
BOOL IsFSecure();
BOOL IsAvast();
BOOL IsNortonInternetSecurity();
BOOL IsKaspersky();
BOOL IsKerio();
BOOL CopySystemDriver(WCHAR* drv_path);
BOOL IsGData();
BOOL IsBlackList();
BOOL doUnhook();
