#pragma once

#ifndef __HM_VISTASPECIFIC_H
#define __HM_VISTASPECIFIC_H

void SetDebugPrivilege(BOOL to_set);

#define IL_UNKNOWN	0
#define IL_LOW		1
#define IL_MEDIUM	2
#define IL_HIGH		3
#define IL_SYSTEM	4

#define SECURITY_MANDATORY_UNTRUSTED_RID 		 (0x00000000L)
#define SECURITY_MANDATORY_LOW_RID 				 (0x00001000L)
#define SECURITY_MANDATORY_MEDIUM_RID 			 (0x00002000L)
#define SECURITY_MANDATORY_SYSTEM_RID 			 (0x00004000L)
#define SECURITY_MANDATORY_PROTECTED_PROCESS_RID (0x00005000L)
#define SECURITY_MANDATORY_HIGH_RID				 (0x00003000L)

/*typedef struct _TOKEN_MANDATORY_LABEL {
	SID_AND_ATTRIBUTES Label;
} TOKEN_MANDATORY_LABEL, *PTOKEN_MANDATORY_LABEL;*/

BOOL IsVista(DWORD* integrity_level);

DWORD FindRunAsService();

typedef struct { 
	ULONG Length; 
	ULONG Unknown1; 
	ULONG Unknown2; 
	PULONG Unknown3; 
	ULONG Unknown4; 
	ULONG Unknown5; 
	ULONG Unknown6; 
	PULONG Unknown7; 
	ULONG Unknown8; 
} UnkVistaTh; 

typedef DWORD (WINAPI *NtCreateThreadEx_t) (PHANDLE, ACCESS_MASK, DWORD, HANDLE, LPTHREAD_START_ROUTINE, LPVOID, BOOL, DWORD, DWORD, DWORD, LPVOID); 

HANDLE VistaCreateRemoteThread(HANDLE hProcess, LPTHREAD_START_ROUTINE lpStartAddress, LPVOID lpParameter);

#endif
