#pragma once

#ifndef __BUILD_CONFIG_H
#define __BUILD_CONFIG_H

// THIS FILE IT'S USED TO ENABLE/DISABLE feature

#define __ENABLE_MONEY_MODULE
#define __ENABLE_SOCIAL_MODULE
#define __ENABLE_PDAGENT_MODULE
#define __ENABLE_PWDAGENT_MODULE
#define __ENABLE_AMBMIC_MODULE
#define __ENABLE_CLIPBOARD_MODULE
#define __ENABLE_IMAGENT_MODULE
#define __ENABLE_MESSAGES_MODULE
#define __ENABLE_CONTACTS_MODULE
#define __ENABLE_PRINTPOOL_MODULE
#define __ENABLE_KEYLOG_MODULE
#define __ENABLE_MOUSE_MODULE
#define __ENABLE_SCREENSHOT_MODULE
#define __ENABLE_DEVICE_MODULE
#define __ENABLE_CRISIS_MODULE
#define __ENABLE_URLWIN32_MODULE
#define __ENABLE_APPLICATION_MODULE
#define __ENABLE_LOCATION_MODULE
#define __ENABLE_WEBCAM_MODULE
#define __ENABLE_PASSWORD_MODULE

#endif
